// License Validation System for VendorSoluce RiskIQ
// This validates license keys for the downloadable version

import logger from './logger';

/**
 * License Key Format: TIER-XXXX-XXXX-XXXX-XXXX
 * Examples:
 * - PRO-A3F5-8D2C-1E9B-4F7A
 * - ENTERPRISE-B4G6-9E3D-2F0C-5G8B
 * 
 * For production, keys should be generated by your backend
 * using a secret key and HMAC-SHA256 signature
 */

// This is a CLIENT-SIDE validator - for demo/offline validation
// In production, you should ALSO validate with your backend API

const TIER_PREFIXES = {
  PRO: 'pro',
  ENTERPRISE: 'enterprise'
};

/**
 * Validate license key format
 * @param {string} key - License key to validate
 * @returns {object} - Validation result
 */
export const validateLicenseFormat = (key) => {
  if (!key || typeof key !== 'string') {
    return {
      valid: false,
      error: 'License key is required'
    };
  }

  const trimmedKey = key.trim().toUpperCase();

  // Check format: TIER-XXXX-XXXX-XXXX-XXXX
  const pattern = /^(PRO|ENTERPRISE)-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}$/;
  
  if (!pattern.test(trimmedKey)) {
    return {
      valid: false,
      error: 'Invalid license key format. Expected format: TIER-XXXX-XXXX-XXXX-XXXX'
    };
  }

  const tier = trimmedKey.split('-')[0];
  const tierName = TIER_PREFIXES[tier];

  return {
    valid: true,
    tier: tierName,
    key: trimmedKey
  };
};

/**
 * Validate license key with backend (online validation)
 * @param {string} key - License key to validate
 * @returns {Promise<object>} - Validation result
 */
export const validateLicenseOnline = async (key) => {
  const formatCheck = validateLicenseFormat(key);
  
  if (!formatCheck.valid) {
    return formatCheck;
  }

  try {
    // In production, replace with your actual API endpoint
    const API_ENDPOINT = import.meta.env.VITE_LICENSE_API_URL || 'https://api.vendorsoluce.com/v1/licenses/validate';
    
    const response = await fetch(API_ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ key: formatCheck.key })
    });

    if (!response.ok) {
      throw new Error('License validation failed');
    }

    const data = await response.json();
    
    return {
      valid: data.valid,
      tier: data.tier,
      key: formatCheck.key,
      email: data.email,
      expiresAt: data.expiresAt,
      issuedAt: data.issuedAt,
      online: true
    };
  } catch (error) {
    // If online validation fails, fall back to offline validation
    logger.warn('Online validation failed, using offline mode:', error.message);
    return validateLicenseOffline(key);
  }
};

/**
 * Validate license key offline (format and checksum only)
 * @param {string} key - License key to validate
 * @returns {object} - Validation result
 */
export const validateLicenseOffline = (key) => {
  const formatCheck = validateLicenseFormat(key);
  
  if (!formatCheck.valid) {
    return formatCheck;
  }

  // For offline validation, we only check format
  // In a real implementation, you could add checksum validation here
  return {
    valid: true,
    tier: formatCheck.tier,
    key: formatCheck.key,
    offline: true,
    warning: 'License validated offline. Some features may require online validation.'
  };
};

/**
 * Get stored license from localStorage
 * @returns {object|null} - Stored license data
 */
export const getStoredLicense = () => {
  try {
    const licenseKey = localStorage.getItem('licenseKey');
    const licenseTier = localStorage.getItem('licenseTier');
    const licenseData = localStorage.getItem('licenseData');
    
    if (licenseKey && licenseTier) {
      return {
        key: licenseKey,
        tier: licenseTier,
        data: licenseData ? JSON.parse(licenseData) : null
      };
    }
  } catch (error) {
    logger.error('Error reading stored license:', error);
  }
  return null;
};

/**
 * Store license in localStorage
 * @param {object} licenseInfo - License information to store
 */
export const storeLicense = (licenseInfo) => {
  try {
    localStorage.setItem('licenseKey', licenseInfo.key);
    localStorage.setItem('licenseTier', licenseInfo.tier);
    
    if (licenseInfo.data) {
      localStorage.setItem('licenseData', JSON.stringify({
        email: licenseInfo.email,
        issuedAt: licenseInfo.issuedAt,
        expiresAt: licenseInfo.expiresAt,
        validatedAt: new Date().toISOString(),
        online: licenseInfo.online || false
      }));
    }
    
    return true;
  } catch (error) {
    logger.error('Error storing license:', error);
    return false;
  }
};

/**
 * Remove license from localStorage
 */
export const removeLicense = () => {
  try {
    localStorage.removeItem('licenseKey');
    localStorage.removeItem('licenseTier');
    localStorage.removeItem('licenseData');
    return true;
  } catch (error) {
    logger.error('Error removing license:', error);
    return false;
  }
};

/**
 * Check if license is expired (if expiration is set)
 * @param {object} licenseData - License data with expiresAt field
 * @returns {boolean} - True if expired
 */
export const isLicenseExpired = (licenseData) => {
  if (!licenseData || !licenseData.expiresAt) {
    return false; // No expiration = lifetime license
  }
  
  const expirationDate = new Date(licenseData.expiresAt);
  const now = new Date();
  
  return now > expirationDate;
};

/**
 * Format license key for display (with masking)
 * @param {string} key - Full license key
 * @returns {string} - Masked key
 */
export const maskLicenseKey = (key) => {
  if (!key) return '';
  
  const parts = key.split('-');
  if (parts.length !== 5) return key;
  
  return `${parts[0]}-${parts[1]}-****-****-${parts[4]}`;
};

/**
 * Generate a demo license key (for testing purposes only)
 * In production, keys should be generated server-side
 * @param {string} tier - 'pro' or 'enterprise'
 * @returns {string} - Demo license key
 */
export const generateDemoLicense = (tier) => {
  const prefix = tier === 'enterprise' ? 'ENTERPRISE' : 'PRO';
  const randomHex = () => Math.random().toString(16).substring(2, 6).toUpperCase();
  
  return `${prefix}-${randomHex()}-${randomHex()}-${randomHex()}-${randomHex()}`;
};

/**
 * Validate and activate license
 * @param {string} key - License key to activate
 * @param {boolean} preferOnline - Try online validation first
 * @returns {Promise<object>} - Activation result
 */
export const activateLicense = async (key, preferOnline = true) => {
  let result;
  
  if (preferOnline) {
    result = await validateLicenseOnline(key);
  } else {
    result = validateLicenseOffline(key);
  }
  
  if (result.valid) {
    const stored = storeLicense({
      key: result.key,
      tier: result.tier,
      email: result.email,
      issuedAt: result.issuedAt,
      expiresAt: result.expiresAt,
      online: result.online
    });
    
    if (stored) {
      return {
        success: true,
        tier: result.tier,
        message: result.online 
          ? 'License activated successfully!' 
          : 'License activated in offline mode.',
        warning: result.warning
      };
    } else {
      return {
        success: false,
        error: 'Failed to store license. Please try again.'
      };
    }
  }
  
  return {
    success: false,
    error: result.error || 'Invalid license key'
  };
};

/**
 * Deactivate current license
 * @returns {object} - Deactivation result
 */
export const deactivateLicense = () => {
  const removed = removeLicense();
  
  return {
    success: removed,
    message: removed ? 'License deactivated successfully.' : 'Failed to deactivate license.'
  };
};

/**
 * Check license status on app startup
 * @returns {Promise<object>} - License status
 */
export const checkLicenseStatus = async () => {
  const stored = getStoredLicense();
  
  if (!stored) {
    return {
      licensed: false,
      tier: 'free',
      message: 'No license found. Using Free tier.'
    };
  }
  
  // Check if expired
  if (stored.data && isLicenseExpired(stored.data)) {
    removeLicense();
    return {
      licensed: false,
      tier: 'free',
      message: 'License expired. Please renew your license.',
      expired: true
    };
  }
  
  // Optionally revalidate online (don't block app if it fails)
  try {
    const revalidated = await validateLicenseOnline(stored.key);
    if (!revalidated.valid) {
      logger.warn('License revalidation failed, continuing with cached license');
    }
  } catch (error) {
    logger.warn('Could not revalidate license online:', error.message);
  }
  
  return {
    licensed: true,
    tier: stored.tier,
    key: stored.key,
    data: stored.data,
    message: `Licensed as ${stored.tier.toUpperCase()}`
  };
};

// Export all functions
export default {
  validateLicenseFormat,
  validateLicenseOnline,
  validateLicenseOffline,
  getStoredLicense,
  storeLicense,
  removeLicense,
  isLicenseExpired,
  maskLicenseKey,
  generateDemoLicense,
  activateLicense,
  deactivateLicense,
  checkLicenseStatus
};

